image:
  name: google/cloud-sdk:alpine
  entrypoint: [""]

stages:
  - Build Image and Send

Production Builder:
  stage: Build Image and Send
  when: manual
  tags:
    - core
  only:
    - tags
  script:
    - |
      export CI_JOB_UNIQUE_SECONDS=$(date +%s)
      export _BUILD_SCRIPTS="
      executor --build-arg BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ) --build-arg BUILD_VERSION=${CI_COMMIT_TAG:-${CI_COMMIT_SHA}} -d 'asia.gcr.io/${GCLOUD_PROJECT_ID}/privypass/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}' --cache=true --cache-ttl=48h -f ./deployment/dockerfile"
      CLOUDSDK_CONFIG=/opt/gcloud-config gcloud builds submit --substitutions _BUILD_SCRIPTS="${_BUILD_SCRIPTS}"

Staging Builder:
  stage: Build Image and Send
  when: manual
  tags:
    - core
  only:
    - staging
  script:
    - |
      export CI_JOB_UNIQUE_SECONDS=$(date +%s)
      export _BUILD_SCRIPTS="
      executor --build-arg BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ) --build-arg BUILD_VERSION=${CI_COMMIT_TAG:-${CI_COMMIT_SHA}} -d 'asia.gcr.io/${GCLOUD_PROJECT_ID}/privypass/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-${CI_JOB_UNIQUE_SECONDS}' --cache=true --cache-ttl=48h -f ./deployment/dockerfile"
      CLOUDSDK_CONFIG=/opt/gcloud-config gcloud builds submit --substitutions _BUILD_SCRIPTS="${_BUILD_SCRIPTS}"

Develop Builder:
  stage: Build Image and Send
  when: manual
  tags:
    - core
  only:
    - develop
    - feature/ci-cd
  script:
    - |
      export CI_JOB_UNIQUE_SECONDS=$(date +%s)
      export _BUILD_SCRIPTS="
      executor --build-arg BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ) --build-arg BUILD_VERSION=${CI_COMMIT_TAG:-${CI_COMMIT_SHA}} -d 'asia.gcr.io/${GCLOUD_PROJECT_ID}/privypass/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-${CI_JOB_UNIQUE_SECONDS}' --cache=true --cache-ttl=48h -f ./deployment/dockerfile"
      CLOUDSDK_CONFIG=/opt/gcloud-config gcloud builds submit --substitutions _BUILD_SCRIPTS="${_BUILD_SCRIPTS}"
