substitutions:
steps:
- name: 'gcr.io/kaniko-project/executor:debug'
  env:
    - "_BUILD_SCRIPTS=${_BUILD_SCRIPTS}"
  entrypoint: /busybox/sh
  args:
    - '-c'
    - |
      ${_BUILD_SCRIPTS}
logsBucket: 'gs://privyplayground_cloudbuild'
options:
  logging: GCS_ONLY
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'E2_HIGHCPU_8'
